### ISSUE TITLE
How to show data of specflow data table

### ISSUE THREAD

**Issue by NgocAnHa** [baev/allure-specflow#2]
When doing with spec-flow integrating allure report, I notice that the data of spec-flow data table dose not include. Is there any setting for showing data of data table in this case OR it does not support in current version (1.2.1)?

**Comment by Bakanych** [comment]
Hi @NgocAnHa, 
Specflow adapter was migrated to Allure 2 and moved here:
https://github.com/allure-framework/allure-csharp

Please consider to use the latest preview version of Specflow.Allure nuget package and Allure 2.* cli to generate report.

You will have table data in your report out of the box.
